<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-AI0OB3V3" name="forgetpassword" tests="1" failures="0" timestamp="15 Apr 2022 14:33:51 GMT" time="0.014" errors="0">
  <testcase name="@BeforeTest initilize" time="0.0" classname="Ecommerice.ValidateForgetPassord">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Resources.Base.intilializeDriver(Base.java:55)
	at Ecommerice.ValidateForgetPassord.initilize(ValidateForgetPassord.java:21)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest initilize -->
  <testcase name="@AfterTest teardown" time="0.0" classname="Ecommerice.ValidateForgetPassord">
    <skipped/>
  </testcase> <!-- @AfterTest teardown -->
  <testcase name="ForgetPasswordRetrieve" time="0.002" classname="Ecommerice.ValidateForgetPassord">
    <skipped/>
  </testcase> <!-- ForgetPasswordRetrieve -->
</testsuite> <!-- forgetpassword -->
